#!/bin/bash

PROJECT_NAME=shukp
COMMON_GROUP_NAME=${PROJECT_NAME}_group
COMMON_USER_NAME=${PROJECT_NAME}
API_KEY=E815CE9F-A81F-4FE5-8FCF-1CE50E81E8C0
API_KEY=123456
APIs="register get_identify_file_path get_report get_brief_report"
AcceptENVs="SHUKP_USERNAME SHUKP_SOURCE_ID SHUKP_SOURCE_NAME SHUKP_TARGET_SHA1 SHUKP_TARGET_SHA1S"

